[package]
name = "magistr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.12.0" }
axum = "0.6.15"
miette = { version = "5.7.0", features = ["fancy"] }
phf = { version = "0.11.1", features = ["macros"] }
rand = "0.8.5"
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["fs", "trace", "compression-full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres"] }
clap = { version = "4.2.7", features = ["derive", "env"] }
thiserror = "1.0.40"
chrono = "0.4.24"
rust-embed = "6.6.1"
mime_guess = "2.0.4"
tower = "0.4.13"
cached = "0.43.0"

[profile.release]
lto = "fat"
strip = "debuginfo"
panic = "abort"
opt-level = "z"
codegen-units = 1
