services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: magistr
      POSTGRES_PASSWORD: password
      POSTGRES_DB: magistr_development
    ports:
    - 127.0.0.1:5432:5432
