name: Continuous Integration

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  actions: read
  contents: read
  checks: write

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, nightly]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Install Rust ${{ matrix.rust }}
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # master
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy
    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.rust }}-
          ${{ runner.os }}-cargo-
    - name: Run Clippy check
      uses: clechasseur/rs-clippy-check@6489db34e7d7a162364f8ee3d7ad2cd1060dc1d7 # v3.0.3
      with:
        args: --all-features
